name: Run All Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean test
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.5
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
          name: Java Tests
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
